apiVersion: apps/v1
kind: Deployment

metadata:
  name: ghs-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ghs-frontend

  template:
    metadata:
      labels:
        app: ghs-frontend

    spec:
      containers:
        - name: frontend
          image: asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/frontend:0544d1d707a5906263ea284d2f80c1fe86956ee7
          ports:
            - containerPort: 80
