apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: student-service

  template:
    metadata:
      labels:
        app: student-service

    spec:
      serviceAccountName: ghs-cloudsql-ksa

      nodeSelector:
          cloud.google.com/gke-nodepool: default-pool-v2

      containers:
        - name: student-service
          image: asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/student-service:0544d1d707a5906263ea284d2f80c1fe86956ee7
          ports:
            - containerPort: 8082

          env:
            - name: DB_URL
              value: jdbc:postgresql://127.0.0.1:5432/ghs_student

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ghs-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghs-db-secret
                  key: DB_PASSWORD 

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.25.4
          args:
            - "--structured-logs"
            - "--port=5432"
            - "project-b1401e3c-6c22-44e2-ba6:asia-south1:ghs-instance"
