apiVersion: apps/v1
kind: Deployment

metadata:
  name: fee-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fee-service

  template:
    metadata:
      labels:
        app: fee-service

    spec:
      containers:
        - name: fee-service
          image: asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/fee-service:d2293207fb749a14a235d075c45f77b8160d3c9d
          ports:
            - containerPort: 8085
