
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghs-networking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kadariravikiran/GHS.git
    targetRevision: qa
    path: k8s/k8s/networking
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

