apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/notification-service:0544d1d707a5906263ea284d2f80c1fe86956ee7
          ports:
            - containerPort: 8090
