apiVersion: apps/v1
kind: Deployment

metadata:
  name: attendance-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: attendance-service

  template:
    metadata:
      labels:
        app: attendance-service

    spec:
      serviceAccountName: ghs-cloudsql-ksa

      nodeSelector:
        cloud.google.com/gke-nodepool: cloudsql-pool

      containers:
        - name: attendance-service
          image: asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/attendance-service:d2293207fb749a14a235d075c45f77b8160d3c9d

          ports:
            - containerPort: 8084

          env:
            - name: DB_URL
              value: jdbc:postgresql://127.0.0.1:5432/attendance_db

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ghs-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghs-db-secret
                  key: DB_PASSWORD

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.25.4

          args:
            - "--structured-logs"
            - "--port=5432"
            - "project-b1401e3c-6c22-44e2-ba6:asia-south1:ghs-instance"
