name: GHS

on:
  push:
    branches:
      - dev
      - qa
      - production

  pull_request:
    branches:
      - dev
      - qa
      - production

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up java 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test all backend services
        run: |
          for service in backend/*-service; do
            echo "Testing $service"
            mvn -f "$service/pom.xml" clean test
          done

      - name: Package all backend services
        run: |
          for service in backend/*-service; do
            echo "Packaging $service"
            mvn -f "$service/pom.xml" package -DskipTests
          done

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-jars
          path: |
            backend/*/target/*.jar 

  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Test frontend
        run: npm test
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/ 

  build-and-push:
    needs:
      - backend-ci
      - frontend-ci

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download backend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-jars
          path: backend

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/887456464145/locations/global/workloadIdentityPools/ghs-pool/providers/githubactions'
          service_account: 'ghs-github-actions@project-b1401e3c-6c22-44e2-ba6.iam.gserviceaccount.com'

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet 

      - name: Build backend Docker images
        run: |
          for service in backend/*-service; do
            echo "Building Docker image for $service"
            docker build \
              -t "asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/$(basename "$service"):${{ github.sha }}" \
              "$service"
          done

      - name: Build frontend Docker image
        run: |
          docker build \
            -t "asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/frontend:${{ github.sha }}" \
            frontend

      - name: Push backend Docker images
        run: |
          for service in backend/*-service; do
            IMAGE="asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/$(basename "$service"):${{ github.sha }}"
            echo "Pushing $IMAGE"
            docker push "$IMAGE"
          done

      - name: Push frontend Docker image
        run: |
          IMAGE="asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/frontend:${{ github.sha }}"
          echo "Pushing $IMAGE"
          docker push "$IMAGE" 


  deploy-to-gke:
    needs:
      - build-and-push

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/887456464145/locations/global/workloadIdentityPools/ghs-pool/providers/githubactions'
          service_account: 'ghs-github-actions@project-b1401e3c-6c22-44e2-ba6.iam.gserviceaccount.com'

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ghs-cluster
          location: asia-south1-a
          project_id: project-b1401e3c-6c22-44e2-ba6

      - name: Deploy frontend
        run: |
          kubectl apply -f k8s/frontend/deployment.yaml
          kubectl apply -f k8s/frontend/service.yaml

          kubectl set image deployment/ghs-frontend \
            frontend=asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/frontend:${{ github.sha }}


      - name: Deploy backend services
        run: |
          for service in k8s/backend/*; do
            echo "Deploying $service"

            SERVICE_NAME=$(basename "$service")

            kubectl apply -f "$service/deployment.yaml"
            kubectl apply -f "$service/service.yaml"

            kubectl set image deployment/$SERVICE_NAME \
              $SERVICE_NAME=asia-south1-docker.pkg.dev/project-b1401e3c-6c22-44e2-ba6/ghs-repo/$SERVICE_NAME:${{ github.sha }}
          done

      - name: Deploy Ingress
        run: |
          kubectl apply -f k8s/ingress/ingress.yaml
